name: examenmiquel
services:
  mysql:
    image: mysql:9.2
    env_file:
      - .env.mysql
    volumes:
      - data-mysql-examenmiquel:/var/lib/mysql
    ports:
      - "3309:3306"
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    ports:
      - "89:80"
    depends_on:
      - mysql
    env_file:
      - .env.mysql

volumes:
  data-mysql-examenmiquel:
